import type { Metadata } from 'next';
import { Inter, Jersey_20_Charted, Roboto_Mono } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import appConfig from '@/util/appConfig';
import { ThemeProvider } from '@/theme/theme.provider';
import { getUserPreferences } from '@/drizzle/actions/user.actions';
import { auth } from '@clerk/nextjs/server';
import { Toaster } from '@/components/ui/toaster';

const robotoMono = Roboto_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { userId } = auth();

  const preferences = await getUserPreferences(userId);

  return (
    <ClerkProvider localization={appConfig.i18n.clerk[locale as 'en' | 'es']}>
      <html lang={locale} suppressHydrationWarning>
        <body className={robotoMono.className}>
          <ThemeProvider attribute="class" defaultTheme={preferences.theme} enableSystem>
            <main>{children}</main>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
