import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { useLocale } from 'next-intl';
import appConfig from '@/util/appConfig';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = useLocale();
  return (
    <ClerkProvider localization={appConfig.i18n.clerk[locale as 'en' | 'es']}>
      <html lang={locale}>
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
